### ISSUE TITLE
Attachment cleanup might result in errors

### ISSUE THREAD

**Issue by gbeaudoin78** [tdharris/dsapp#53]
After running a few check with dsapp, I've started to receive a few errors about attachment.

ERROR [POPULATE_WORKER_Thread-9] [gwconnectorlogic:1813] [userID:xxxxxx] [eventID:] [objectID:] [AttachmentsDownload] Failure sending attachment xxxxxx to engine

I suspect the order of the maintenance task.

At line 5267 you delete the attachments file on the filesystem. At line 5268 you delete the database record.

If the operation is aborted during the filesystem cleanup (using Ctrl-C), we might end up with database records with the attachment file removed from the filesystem.

I suggest deleting the records from the database then delete the files.

**Comment by gbeaudoin78** [comment]
dsapp.sh itself is not on github? :(

**Comment by snielson** [comment]
Assigned this to Tyler.
Do you want to check out your cleanup function, and make the suggested fixes?
