### ISSUE TITLE
BES enabled BB10 devices with MDM configured in GMS doesn't list device OS version

### ISSUE THREAD

**Issue by smsengineering** [tdharris/dsapp#63]
IF GMS is configured with the IP address of MDM server pointing to a BES12 server, and BlackBerry 10 devices are activated through the BES, their OS does not show up in the User Info > List all devices from DB, instead they all list as MDM
![dsapp mdm os](https://cloud.githubusercontent.com/assets/13456435/8834090/e5654824-3077-11e5-9b7d-2a5fff624b87.PNG)

**Comment by snielson** [comment]
Need to investigate description column in the devices table. This may be a limitation of what is stored in the database by GMS, as we simply do a select query.

**Comment by smsengineering** [comment]
All the info is there, just has to be parsed differently when the mdm is
prepended. I think thats how the gms team handled it for the dashboard 

Sent from my BlackBerry 10 smartphone on the Rogers network.

**Comment by snielson** [comment]
GMS developers have an open defect to get the correct device information, if GMS is configured to use a MDM server.

Once GMS has this fix, the dsapp display devices should output the proper information.
