### ISSUE TITLE
running dsapp under crontab

### ISSUE THREAD

**Issue by ipsec** [tdharris/dsapp#64]
Hi all,

I'm trying to run dsapp under cron, but dsapp stop and start cron inside itself.
I think dsapp is killing (sigterm) the cron threads and does not run the rccron start right. The term signal does not finish immediately before rccron start so this command does not run.

After dsapp run over crontab the cron service is dead.

**Comment by snielson** [comment]
I assume you mean the the vacuum and index switch?
dsapp v221 uses a crude PID tracking method,  but was simple attempt to deal with the ~/.pgpass file

The vacuum and index used a stop and start method that would end the cron process, but this was mainly put in to stop mobility from starting during and upgrade or other database tasks.

Rather then killing cron in the vacuum and index switch (no need to stop cron here), I've adjusted the stop and start for the vacuum and index. This no longer stops cron.

I'll look into adjusting the script more, to function better with a PID file

**Comment by snielson** [comment]
dsapp v222 has a workaround to not stop cron during a vacuum and index.
Rewriting script in python, which will include better PID handling
