### ISSUE TITLE
Typo in generate self signed cert

### ISSUE THREAD

**Issue by openhardwarecoza** [tdharris/dsapp#66]
https://github.com/tdharris/dsapp/blob/master/dsapp-test.sh#L2207

reads:

 openssl req -she256 -new -key server.key -out server.csr -passin pass:${pass};

should be 

 openssl req -sha256 -new -key server.key -out server.csr -passin pass:${pass};

**Comment by snielson** [comment]
Thanks for the find / report.
Fixed v223
