### ISSUE TITLE
dsapp script is not correctly detecting new GMS 2.2 (14.0.x) version

### ISSUE THREAD

**Issue by wmeens** [tdharris/dsapp#68]
Hi,

As reported in vibe.novell.com GMS TP forums:
Issue:
The dsapp script is trying to stop datasync services instead of gms.
The result is that the script is running a vacuum and re-index while the GMS service is up and running!!    Not good.

Steps to reproduce:

Install or upgrade to GMS 2.2
Install dsapp (in my case version 225 of the script is running)
run "/opt/novell/datasync/tools/dsapp/dsapp.sh -v -i"
 
What's needed:

Script should be updated, as it now looks for $ds_20x (a value of 2000), and the version in /opt/novell/datasync/version states 14.2.0.x
As I quick workaround I've set ds_20x to 14, but this will be undone with the next dsapp autoupdate.

Thanks,
  Willem

**Comment by snielson** [comment]
Hi Willem,

Thanks I'll look into this and get the script updated to work with the new version format (or use a different method to check versions)

-Shane

**Comment by wmeens** [comment]
Hi Shane,

Thanks for your quick follow-up and for looking into this.

Also, thanks for a great tool.  I've don't leave a GMS install running
without adding this tool in. :)

Cheers,
  Willem 
>>> snielson <notifications@github.com> 1-12-2015 20:31 >>>
Hi Willem,
Thanks I'll look into this and get the script updated to work with the
new version format (or use a different method to check versions)
-Shane
—
Reply to this email directly or view it on GitHub
( https://github.com/tdharris/dsapp/issues/68#issuecomment-161071270)
.

**Comment by snielson** [comment]
Fix in v226 and newer
