### ISSUE TITLE
226 SOAP issue

### ISSUE THREAD

**Issue by bahsig** [tdharris/dsapp#69]
With secure SOAP enabled it is not possible check user or Groupwise Folder Structure. "SOAP poa:7191 secure. Cannot complete".

**Comment by snielson** [comment]
The failure to connect to secure soap message was added on purpose. The method to make a secure SOAP client / connection via bash was a huge task, and we decided to leave it out.

However I've been rewritting the entire dsapp code, into python, where the secure SOAP works.
https://github.com/snielson/dsapp_python

The python version is not complete at this time, but should solve this issue once released.

**Comment by bahsig** [comment]
thx for information.
